/**
 * @Author : nopsky
 * @Email : cnnopsky@gmail.com
 * @Date : 2021/9/18 11:31
 */
package model

var fileTmplRaw = `// Code generated by Kirito. DO NOT EDIT.
package {{.Package}}
{{if .ImportPath}}
import (
	{{- range .ImportPath}}
	"{{.}}"
	{{- end}}
)
{{- end}}

{{- if .StructCode.Comment -}}
// {{.StructCode.Comment}}
{{- end}}

type {{.StructCode.TableName}} struct {
{{- range .StructCode.Fields}}
	{{.Name}} {{.GoType}} {{if .Tag}}` + "`{{.Tag}}`" + `{{end}}{{if .Comment}} // {{.Comment}}{{end}}
{{- end}}
}
{{if .StructCode.NameFunc}}
func (m *{{.StructCode.TableName}}) TableName() string {
	return "{{.StructCode.RawTableName}}"
}
{{end}}
`
